### ISSUE TITLE
Curious question, not issue

### ISSUE THREAD

**Issue by rmathewsbeyond** [mcasalaina/epbnbascratchorg#3]
Hi,
I'm trying to enable Einstein Predictions Builder in my scratch org, and googling led me to this repo. I see in your scratch org definition file you have a 'template' defined, I don't have that in my org.

Which leads me to believe either you have a custom field 'template' on the ScratchOrgInfo object or you have an add-on or feature from salesforce.

I'm still looking for ways to enable prediction builder in scratch orgs, and if you have done kindly share how.

**Comment by mcasalaina** [comment]
Hello! Actually the trick is to set the EinsteinBuilderFree feature in your scratch org features (as noted in [this doc](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm)). In this case I used a template because I wanted it to come with a bunch of other preconfigured things and data for the workshops we run from these orgs.

Please let me know if I can be of any further assistance.
